version: "3"

services:
  mosaic:
    build: .
    environment:
      - OAM_LAYER_ID=openaerialmap
      - PORT=8001
      - PGHOST=postgres
      - PGUSER=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres
      - DB_DISABLE_SSL=true
      - TITILER_BASE_URL=http://titiler:8000
      - BASE_URL=http://localhost:8001
      - TILES_CACHE_DIR_PATH=/tiles
    ports:
      - 8001:8001
    depends_on:
      - postgres
      - titiler
    volumes:
      - ./tiles:/tiles
      - ./src/:/usr/src/app/src
    command: npm run dev

  postgres:
    build:
      context: ./postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  titiler:
    image: developmentseed/titiler
    environment:
      - PORT=8000
      - WORKERS_PER_CORE=1
    ports:
      - 8000:8000
