version: "3.9"

services:
  oam-downloader:
    build: .
    environment:
      - WORKDIR=images
      - BBOX=bbox=27.44704,53.83303,27.70474,53.97516
    volumes:
      - .\oam_images:/home/oam-downloader/images