apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: raster-tiler
  namespace: dev-mosaic
  labels:
    app.kubernetes.io/managed-by: manually
    app.kubernetes.io/name: raster-tiler
    app.kubernetes.io/instance: raster-tiler-abcxzy
    app.kubernetes.io/component: backend
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: local-path
  volumeMode: Filesystem
