--- # Time-stamp: <2022-09-20 15:58:15>

name: 01 Building with Docker

'on':
  - push
  - fork

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Building with Docker
        working-directory: ./mosaic-tiler
        env:
          NEXUS_NPM_TOKEN: ${{ secrets.NEXUS_NPM_TOKEN }}
          NEXUS_DEPLOYER: ${{ secrets.NEXUS_DEPLOYER }}
          NEXUS_DEPLOYER_PASS: ${{ secrets.NEXUS_DEPLOYER_PASS }}
        run: |-
          set -e

          wget -q https://kontur-github-runners.s3.eu-central-1.amazonaws.com/public_resources/projects/common/2022091500.tar.xz && tar -C "$HOME" -xf 2022091500.tar.xz && rm 2022091500.tar.xz

          echo '${{ secrets.NEXUS_DEPLOYER_PASS }}' | docker login nexus.kontur.io:8085 -u '${{ secrets.NEXUS_DEPLOYER }}' --password-stdin

          echo "Build docker image"
          docker build -t nexus.kontur.io:8084/konturdev/raster-tiler:latest -f Dockerfile .

          echo "Push docker image"
          docker push nexus.kontur.io:8084/konturdev/raster-tiler:latest
